feat(submit): support authentication in submit action (#746)
* feat: support authentication in submit action
* chore: document authentication in submit action

diff --git a/.github/actions/submit/action.yaml b/.github/actions/submit/action.yaml
--- a/.github/actions/submit/action.yaml
+++ b/.github/actions/submit/action.yaml
@@ -22,6 +22,12 @@ inputs:
   attachments-relative-to:
     description: The reference directory for relative attachment paths
     required: false
+  client-id:
+    description: Client ID for jobs requiring authentication
+    required: false
+  secret-key:
+    description: Secret key for jobs requiring authentication
+    required: false
 outputs:
   id:
     description: 'The ID of the submitted job'
@@ -145,13 +151,25 @@ runs:
       env:
         SERVER: https://${{ inputs.server }}
         RELATIVE_TO: ${{ inputs.attachments-relative-to }}
+        CLIENT_ID: ${{ inputs.client-id }}
+        SECRET_KEY: ${{ inputs.secret-key }}
         JOB: ${{ steps.create-job-file.outputs.job }}
       run: |
         echo "::group::Submit job to the Testflinger server"
-        if [ -n "$RELATIVE_TO" ]; then
-          RELATIVE="--attachments-relative-to $RELATIVE_TO"
-        fi
-        JOB_ID=$(testflinger --server $SERVER submit --quiet $RELATIVE "$JOB")
+        AUTH_ARGS_COUNT=0
+        [[ -n $CLIENT_ID ]] && ((++AUTH_ARGS_COUNT))
+        [[ -n $SECRET_KEY ]] && ((++AUTH_ARGS_COUNT))
+        case $AUTH_ARGS_COUNT in
+            0) AUTH_ARGS=() ;;
+            2) AUTH_ARGS=( --client_id "$CLIENT_ID" --secret_key "$SECRET_KEY" ) ;;
+            1) echo "::error::Both 'client-id' and 'secret-key' must be provided or neither"; exit 1 ;;
+        esac
+        JOB_ID=$(\
+          testflinger --server "$SERVER" submit --quiet \
+          ${RELATIVE_TO:+--attachments-relative-to "$RELATIVE_TO"} \
+          "${AUTH_ARGS[@]}" \
+          "$JOB" \
+        )
         echo "id=$JOB_ID" >> $GITHUB_OUTPUT
         echo "::endgroup::"
         echo "::notice::Submitted job $JOB_ID"
