chore(actions): move diagnostic step to the very beginning

diff --git a/.github/actions/submit/action.yaml b/.github/actions/submit/action.yaml
--- a/.github/actions/submit/action.yaml
+++ b/.github/actions/submit/action.yaml
@@ -22,6 +22,22 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Test connection to Testflinger server
+      shell: bash {0}  # allow curl to fail
+      env:
+        SERVER: https://${{ inputs.server }}
+      run: |
+        STATUS=$(curl -I -w "%{http_code}\n" -o /dev/null -s $SERVER/jobs)
+        ERROR=$?
+        if [ ! $ERROR -eq 0 ]; then
+          echo "Unable to ping Testflinger server at $SERVER"
+          exit $ERROR
+        elif [ ! $STATUS -eq 200 ]; then
+          echo "Failed server ping at $SERVER, error status: $STATUS"
+          exit $STATUS
+        else
+          echo "Successful server ping at $SERVER, status: $status"
+        fi
     - name: Create job file, if required
       id: create-job-file
       shell: bash
@@ -52,22 +68,6 @@ runs:
       shell: bash
       run: sudo snap install testflinger-cli jq
 
-    - name: Test connection to Testflinger server
-      shell: bash {0}  # allow curl to fail
-      env:
-        SERVER: https://${{ inputs.server }}
-      run: |
-        STATUS=$(curl -I -w "%{http_code}\n" -o /dev/null -s $SERVER/jobs)
-        ERROR=$?
-        if [ ! $ERROR -eq 0 ]; then
-          echo "Unable to ping Testflinger server at $SERVER"
-          exit $ERROR
-        elif [ ! $STATUS -eq 200 ]; then
-          echo "Failed server ping at $SERVER, error status: $STATUS"
-          exit $STATUS
-        else
-          echo "Successful server ping at $SERVER, status: $status"
-        fi
     - name: Submit job to the Testflinger server
       id: submit
       if: inputs.dry-run != 'true'
