feat: add workflow groups

diff --git a/.github/actions/submit/action.yaml b/.github/actions/submit/action.yaml
--- a/.github/actions/submit/action.yaml
+++ b/.github/actions/submit/action.yaml
@@ -34,6 +34,7 @@ runs:
       env:
         SERVER: https://${{ inputs.server }}
       run: |
+        echo "::group::Test connection to Testflinger server"
         STATUS=$(curl --stderr error.log -Ivw "%{http_code}\n" -o /dev/null $SERVER/jobs)
         ERROR=$?
         if [ ! $ERROR -eq 0 ]; then
@@ -47,11 +48,13 @@ runs:
         else
           echo "Successful server ping at $SERVER, status: $STATUS"
         fi
+        echo "::endgroup::"
 
     - name: Create job file, if required
       id: create-job-file
       shell: bash
       run: |
+        echo "::group::Create job file (if required)"
         if [ -n "${{ inputs.job-path }}" ]; then
         # the `$JOB` environment variable points to the job path provided as input
         echo "JOB=${{ inputs.job-path }}" >> $GITHUB_ENV
@@ -69,25 +72,34 @@ runs:
         # the `$JOB` environment variable points to the newly created job file
         echo "JOB=$FILE" >> $GITHUB_ENV
         fi
+        echo "::endgroup::"
 
     - name: Display contents of job file (for verification)
       shell: bash
-      run: cat "$JOB"
+      run: |
+        echo "::group::Display job file"
+        cat "$JOB"
+        echo "::endgroup::"
 
     - name: Determine if this is a reservation job
       id: check-reservation
       shell: bash
       run: |
+        echo "::group::Determine if this is a reservation job"
         if grep -q "^reserve_data:" $JOB; then
           RESERVATION=true
         else
           RESERVATION=false
         fi
         echo "reservation=$RESERVATION" | tee -a $GITHUB_OUTPUT
+        echo "::endgroup::"
 
     - name: Install prerequisites
       shell: bash
-      run: sudo snap install testflinger-cli jq
+      run: |
+        echo "::group::Install prerequisites"
+        sudo snap install testflinger-cli jq
+        echo "::endgroup::"
 
     - name: Submit job to the Testflinger server
       id: submit
@@ -97,12 +109,14 @@ runs:
         SERVER: https://${{ inputs.server }}
         RELATIVE_TO: ${{ inputs.attachments-relative-to }}
       run: |
+        echo "::group::Submit job to the Testflinger server"
         if [ -n "$RELATIVE_TO" ]; then
           RELATIVE="--attachments-relative-to $RELATIVE_TO"
         fi
         JOB_ID=$(testflinger --server $SERVER submit --quiet "$RELATIVE" "$JOB")
         echo "job id: $JOB_ID"
         echo "id=$JOB_ID" >> $GITHUB_OUTPUT
+        echo "::endgroup::"
 
     - name: Track the status of the job (non-reservation)
       if: inputs.poll == 'true' && inputs.dry-run != 'true' && steps.check-reservation.outputs.reservation != 'true'
@@ -111,47 +125,11 @@ runs:
         SERVER: https://${{ inputs.server }}
         JOB_ID: ${{ steps.submit.outputs.id }}
       run: |
+        echo "::group::Track the status of the job"
         # poll
         PYTHONUNBUFFERED=1 testflinger --server $SERVER poll $JOB_ID
-
-    - name: Track the status of the job (reservation)
-      if: inputs.poll == 'true' && inputs.dry-run != 'true' && steps.check-reservation.outputs.reservation == 'true'
-      shell: bash
-      env:
-        SERVER: https://${{ inputs.server }}
-        JOB_ID: ${{ steps.submit.outputs.id }}
-        TERMINATION: "TESTFLINGER SYSTEM RESERVED"
-      run: |
-        # specify file for capturing output and clear it
-        CAPTURED_OUTPUT=output
-        > "$CAPTURED_OUTPUT"
-        # perform one-shot polling until the reserve phase has been reached
-        # and the captured out contains the TERMINATION string
-        while true; do
-          PYTHONUNBUFFERED=1 testflinger --server $SERVER poll --oneshot $JOB_ID | tee -a "$CAPTURED_OUTPUT"
-          JOB_STATUS="$(testflinger --server $SERVER status $JOB_ID)"
-          if [ "$JOB_STATUS" = "reserve" ]; then
-            if grep -q "$TERMINATION" "$CAPTURED_OUTPUT"; then
-              EXIT_STATUS=0
-              break
-            fi
-          elif [[ "$JOB_STATUS" =~ ^(complete|cancelled)$ ]]; then
-            EXIT_STATUS=1
-            break
-          fi
-          sleep 10
-        done
-        echo "Reserve exit status: $EXIT_STATUS"
-        exit $EXIT_STATUS
-
-    - name: Retrieve job results and compute exit status
-      if: inputs.poll == 'true' && inputs.dry-run != 'true' && steps.check-reservation.outputs.reservation != 'true'
-      shell: bash
-      env:
-        SERVER: https://${{ inputs.server }}
-        JOB_ID: ${{ steps.submit.outputs.id }}
-      run: |
-        # retrieve results:
+        echo "::endgroup::"
+        echo "::group::Retrieve job results, determine exit status"
         # the exit status is the maximum status of the individual test phases
         # (excluding the setup and cleanup phases)
         EXIT_STATUS=$(\
@@ -168,6 +146,39 @@ runs:
         )
         echo "Test exit status: $EXIT_STATUS"
         exit $EXIT_STATUS
+        echo "::endgroup::"
+
+    - name: Track the status of the job (reservation)
+      if: inputs.poll == 'true' && inputs.dry-run != 'true' && steps.check-reservation.outputs.reservation == 'true'
+      shell: bash
+      env:
+        SERVER: https://${{ inputs.server }}
+        JOB_ID: ${{ steps.submit.outputs.id }}
+        TERMINATION: "TESTFLINGER SYSTEM RESERVED"
+      run: |
+        echo "::group::Track the status of the reservation job"
+        # specify file for capturing output and clear it
+        CAPTURED_OUTPUT=output
+        > "$CAPTURED_OUTPUT"
+        # perform one-shot polling until the reserve phase has been reached
+        # and the captured output contains the TERMINATION string
+        while true; do
+          PYTHONUNBUFFERED=1 testflinger --server $SERVER poll --oneshot $JOB_ID | tee -a "$CAPTURED_OUTPUT"
+          JOB_STATUS="$(testflinger --server $SERVER status $JOB_ID)"
+          if [ "$JOB_STATUS" = "reserve" ]; then
+            if grep -q "$TERMINATION" "$CAPTURED_OUTPUT"; then
+              EXIT_STATUS=0
+              break
+            fi
+          elif [[ "$JOB_STATUS" =~ ^(complete|cancelled)$ ]]; then
+            EXIT_STATUS=1
+            break
+          fi
+          sleep 10
+        done
+        echo "Reserve exit status: $EXIT_STATUS"
+        exit $EXIT_STATUS
+        echo "::endgroup::"
 
     - name: Cancel the job if the action is cancelled
       if: ${{ cancelled() }}
@@ -176,4 +187,6 @@ runs:
         SERVER: https://${{ inputs.server }}
         JOB_ID: ${{ steps.submit.outputs.id }}
       run: |
+        echo "::group::Cancel job"
         testflinger --server $SERVER cancel $JOB_ID
+        echo "::endgroup::"
