Validate charm promote inputs

diff --git a/.github/workflows/charm-promote.yml b/.github/workflows/charm-promote.yml
--- a/.github/workflows/charm-promote.yml
+++ b/.github/workflows/charm-promote.yml
@@ -33,6 +33,12 @@ jobs:
   promote-charm:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate inputs
+        run: |
+          if [ "${{ inputs.destination-channel }}" == "${{ inputs.origin-channel }}" ]; then
+            echo "Error: Destination and origin channels cannot be the same."
+            exit 1
+          fi
       - uses: actions/checkout@v4
       - name: Promote Charm
         uses: canonical/charming-actions/promote-charm@2.7.0
